import { StyleSheet } from 'react-native';
import { Theme } from './theme';

const colors = {
  bg: Theme.colors.bg,
  surface: Theme.colors.card,
  surfaceSoft: Theme.colors.surfaceSoft,
  primary: Theme.colors.primary,
  primaryDeep: Theme.colors.primaryDeep,
  primaryLight: Theme.colors.primaryLight,
  text: Theme.colors.textPrimary,
  textMuted: Theme.colors.textSecondary,
  border: Theme.colors.border,
  success: '#849D8E',
  successLight: '#E7EFEA',
  warning: '#B99162',
  warningLight: '#F4EBDD',
  risk: '#B4776E',
  riskLight: '#F3E5E1',
};

const softShadow = {
  ...Theme.shadow.paper,
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.bg },
  app: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    minHeight: 52,
    paddingTop: 4,
    paddingBottom: 4,
  },
  headerCompact: { minHeight: 52, paddingHorizontal: 12 },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  kicker: { color: colors.primaryDeep, fontSize: 12, fontWeight: '700', marginBottom: 4 },
  largeTitle: { color: colors.text, fontSize: 24, lineHeight: 30, fontWeight: '800', letterSpacing: 0 },
  largeTitleCompact: { fontSize: 21, lineHeight: 27 },
  navigationBar: {
    zIndex: 10,
    elevation: 3,
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: -16,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
    backgroundColor: colors.bg,
  },
  navigationBarFixed: { marginHorizontal: 0 },
  navigationSide: { width: 64, alignItems: 'center', justifyContent: 'center' },
  navigationSideCompact: { width: 48 },
  navigationBack: { color: colors.primaryDeep, fontSize: 34, fontWeight: '400', lineHeight: 38 },
  navigationTitle: { flex: 1, color: colors.text, fontSize: 17, fontWeight: '800', textAlign: 'center' },
  navigationTitleCompact: { fontSize: 15 },
  navigationAction: { color: colors.primaryDeep, fontSize: 14, fontWeight: '800' },
  addButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    backgroundColor: colors.primaryLight,
  },
  addButtonText: { color: colors.primaryDeep, fontSize: 24, fontWeight: '500', marginTop: -2 },
  content: { width: '100%', gap: 12, paddingHorizontal: 16, paddingBottom: 110 },
  contentCompact: { gap: 12, paddingHorizontal: 12 },
  contentWide: { maxWidth: 720, alignSelf: 'center' },
  hrDemoScreen: { flex: 1, backgroundColor: colors.bg },
  hrDemoNav: { minHeight: 52, flexDirection: 'row', alignItems: 'center', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border, backgroundColor: colors.bg },
  hrDemoNavButton: { width: 56, minHeight: 48, alignItems: 'center', justifyContent: 'center' },
  hrDemoNavSide: { width: 92, minHeight: 48, alignItems: 'center', justifyContent: 'center' },
  hrDemoNavTitle: { flex: 1, color: colors.text, fontSize: 17, lineHeight: 22, fontWeight: '800', textAlign: 'center' },
  hrDemoPrivacyLabel: { paddingHorizontal: 8, paddingVertical: 5, overflow: 'hidden', borderRadius: 7, color: '#4B5563', backgroundColor: colors.surfaceSoft, fontSize: 11, lineHeight: 15, fontWeight: '700' },
  hrDemoContent: { width: '100%', maxWidth: 720, alignSelf: 'center', gap: 18, paddingHorizontal: 16, paddingTop: 18, paddingBottom: 36 },
  hrDemoHeader: { gap: 5 },
  hrDemoHeaderTopline: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  hrDemoCompany: { flex: 1, minWidth: 0, color: colors.text, fontSize: 24, lineHeight: 30, fontWeight: '800' },
  hrDemoStatus: { flexShrink: 0, paddingHorizontal: 9, paddingVertical: 5, overflow: 'hidden', borderRadius: 7, color: Theme.colors.status.success.text, backgroundColor: Theme.colors.status.success.bg, fontSize: 12, lineHeight: 16, fontWeight: '800' },
  hrDemoRole: { color: colors.text, fontSize: 17, lineHeight: 23, fontWeight: '700' },
  hrDemoMeta: { color: colors.textMuted, fontSize: 13, lineHeight: 19 },
  hrDemoSegmented: { flexDirection: 'row', gap: 3, padding: 3, borderRadius: 10, backgroundColor: '#ECEFED' },
  hrDemoSegment: { flex: 1, minHeight: 40, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 6, borderRadius: 8 },
  hrDemoSegmentActive: { backgroundColor: colors.surface, ...softShadow },
  hrDemoSegmentText: { color: colors.textMuted, fontSize: 14, lineHeight: 19, fontWeight: '700' },
  hrDemoSegmentTextActive: { color: colors.text },
  hrDemoSectionStack: { gap: 18 },
  hrDemoConclusion: { gap: 10, paddingVertical: 6 },
  hrDemoEyebrow: { color: colors.primaryDeep, fontSize: 12, lineHeight: 17, fontWeight: '800' },
  hrDemoConclusionTitle: { color: colors.text, fontSize: 22, lineHeight: 29, fontWeight: '800' },
  hrDemoBody: { color: '#374151', fontSize: 15, lineHeight: 24 },
  hrDemoMetricGrid: { flexDirection: 'row', overflow: 'hidden', borderWidth: StyleSheet.hairlineWidth, borderColor: colors.border, borderRadius: 10, backgroundColor: colors.surface },
  hrDemoMetric: { flex: 1, minWidth: 0, alignItems: 'center', gap: 3, paddingHorizontal: 4, paddingVertical: 14, borderRightWidth: StyleSheet.hairlineWidth, borderRightColor: colors.border },
  hrDemoMetricInteractive: { backgroundColor: '#F7F5FC' },
  hrDemoMetricValue: { alignSelf: 'stretch', minWidth: 56, color: colors.text, fontSize: 21, lineHeight: 28, fontWeight: '800', textAlign: 'center', fontVariant: ['tabular-nums'] },
  hrDemoMetricLabel: { color: colors.textMuted, fontSize: 11, lineHeight: 16, fontWeight: '600', textAlign: 'center' },
  hrDemoPlainSection: { gap: 10, paddingVertical: 3 },
  hrDemoSectionTitle: { color: colors.text, fontSize: 16, lineHeight: 22, fontWeight: '800' },
  hrDemoProgressRow: { minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 9, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border },
  hrDemoProgressIcon: { width: 30, height: 30, alignItems: 'center', justifyContent: 'center', borderRadius: 8, backgroundColor: colors.primaryLight },
  hrDemoProgressTitle: { flexShrink: 0, color: colors.text, fontSize: 14, lineHeight: 19, fontWeight: '700' },
  hrDemoProgressDetail: { flex: 1, minWidth: 0, color: colors.textMuted, fontSize: 12, lineHeight: 17, textAlign: 'right' },
  hrDemoPrimaryAction: { minHeight: 50, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, paddingHorizontal: 18, borderRadius: 10, backgroundColor: colors.primaryDeep },
  hrDemoPrimaryActionText: { color: colors.surface, fontSize: 15, lineHeight: 20, fontWeight: '800' },
  hrDemoPrivacyNote: { flexDirection: 'row', alignItems: 'flex-start', gap: 9, padding: 14, borderRadius: 10, backgroundColor: Theme.colors.status.success.bg },
  hrDemoPrivacyText: { flex: 1, minWidth: 0, color: '#355047', fontSize: 12, lineHeight: 18 },
  hrDemoAudioSummary: { minHeight: 66, flexDirection: 'row', alignItems: 'center', gap: 10, padding: 12, borderRadius: 10, backgroundColor: '#F5F3FF' },
  hrDemoAudioIcon: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: 20, backgroundColor: '#EDE9FE' },
  hrDemoFlex: { flex: 1, minWidth: 0 },
  hrDemoAudioTitle: { color: colors.text, fontSize: 14, lineHeight: 20, fontWeight: '800' },
  hrDemoSmall: { color: colors.textMuted, fontSize: 11, lineHeight: 16 },
  hrDemoDemoOnly: { flexShrink: 0, color: '#6D5A94', fontSize: 10, lineHeight: 14, fontWeight: '700' },
  hrDemoEvidenceList: { overflow: 'hidden', borderRadius: 10, backgroundColor: colors.surface },
  hrDemoEvidenceItem: { gap: 8, paddingHorizontal: 16, paddingTop: 16 },
  hrDemoEvidenceMeta: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  hrDemoSpeaker: { color: colors.primaryDeep, fontSize: 12, lineHeight: 17, fontWeight: '800' },
  hrDemoTimeLabel: { minWidth: 76, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4, paddingHorizontal: 7, paddingVertical: 3, borderRadius: 6, backgroundColor: '#F5F3FF' },
  hrDemoTimeText: { minWidth: 42, color: '#6D5A94', fontSize: 11, lineHeight: 16, fontWeight: '700', textAlign: 'center', fontVariant: ['tabular-nums'] },
  hrDemoEvidenceTitle: { color: colors.text, fontSize: 15, lineHeight: 21, fontWeight: '800' },
  hrDemoDivider: { height: StyleSheet.hairlineWidth, marginTop: 8, backgroundColor: colors.border },
  hrDemoEvidenceReference: { alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 5, overflow: 'hidden', borderRadius: 6, color: '#6D5A94', backgroundColor: '#F5F3FF', fontSize: 11, lineHeight: 16, fontWeight: '700' },
  hrDemoActionSection: { gap: 2, padding: 16, borderRadius: 10, backgroundColor: colors.surface },
  hrDemoActionRow: { minHeight: 46, flexDirection: 'row', alignItems: 'center', gap: 10, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border },
  hrDemoActionIndex: { width: 24, height: 24, overflow: 'hidden', borderRadius: 12, color: colors.primaryDeep, backgroundColor: colors.primaryLight, fontSize: 12, lineHeight: 24, fontWeight: '800', textAlign: 'center' },
  hrDemoActionBody: { flex: 1, minWidth: 0, color: '#374151', fontSize: 14, lineHeight: 20 },
  heroGroup: { gap: 10, padding: 18, borderRadius: 18, backgroundColor: colors.surface, ...softShadow },
  heroTitle: { color: colors.text, fontSize: 24, fontWeight: '800', lineHeight: 30 },
  mutedText: { color: colors.textMuted, fontSize: 14, lineHeight: 20 },
  cardScroller: { marginHorizontal: -16, paddingHorizontal: 16 },
  todayInterviewCard: {
    minHeight: 142,
    justifyContent: 'space-between',
    gap: 12,
    marginRight: 10,
    padding: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: colors.surface,
    ...softShadow,
  },
  todayInterviewCardPrimary: {
    borderColor: '#D8C7B5',
    backgroundColor: '#FFFCF8',
  },
  sectionHeadingRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  sectionMeta: { marginRight: 4, color: colors.textMuted, fontSize: 12, fontWeight: '600' },
  interviewCardTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  interviewCardEyebrow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  interviewTime: { color: colors.primaryDeep, fontSize: 13, fontWeight: '800' },
  interviewCountdown: { overflow: 'hidden', borderRadius: 6, paddingHorizontal: 8, paddingVertical: 4, color: colors.primaryDeep, backgroundColor: colors.primaryLight, fontSize: 11, fontWeight: '800' },
  interviewStatus: { color: colors.textMuted, fontSize: 12, fontWeight: '700' },
  interviewCardMain: { gap: 4 },
  interviewCompany: { color: colors.text, fontSize: 21, fontWeight: '800', lineHeight: 27 },
  interviewRole: { color: colors.text, fontSize: 15, fontWeight: '700', lineHeight: 21 },
  interviewMeta: { color: colors.textMuted, fontSize: 13, lineHeight: 19 },
  interviewCardFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', gap: 10 },
  interviewProgress: { flexShrink: 0, minWidth: 66, color: colors.textMuted, fontSize: 12, fontWeight: '700', textAlign: 'right', fontVariant: ['tabular-nums'] },
  interviewProgressTrack: { width: 86, height: 4, overflow: 'hidden', borderRadius: 2, backgroundColor: colors.border },
  interviewProgressFill: { height: 4, borderRadius: 2, backgroundColor: colors.primaryDeep },
  interviewCardAction: { color: colors.primaryDeep, fontSize: 13, fontWeight: '800' },
  compactChevron: { color: colors.primary, fontSize: 20, lineHeight: 20 },
  metricGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  metricCard: {
    width: '100%',
    minHeight: 86,
    justifyContent: 'space-between',
    padding: 14,
    borderRadius: 12,
    backgroundColor: colors.surface,
    ...softShadow,
  },
  metricLabel: { color: colors.textMuted, fontSize: 13, fontWeight: '600' },
  metricValue: { color: colors.text, fontSize: 28, fontWeight: '800' },
  offerMetricValue: {
    minWidth: 0,
    color: colors.text,
    fontSize: 20,
    lineHeight: 26,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
  },
  funnelCard: {
    gap: 18,
    paddingVertical: 10,
  },
  funnelStage: {
    gap: 9,
    minHeight: 48,
  },
  funnelStageHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  funnelStageLabel: { color: colors.text, fontSize: 15, fontWeight: '700' },
  funnelStageValueRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  funnelStageValue: { color: colors.text, fontSize: 17, fontWeight: '800' },
  funnelValueLine: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  funnelRate: { minWidth: 36, overflow: 'hidden', borderRadius: 5, paddingHorizontal: 6, paddingVertical: 2, color: colors.textMuted, backgroundColor: colors.surfaceSoft, fontSize: 10, lineHeight: 14, fontWeight: '800', textAlign: 'center' },
  funnelRatePositive: { color: '#4F735E', backgroundColor: colors.successLight },
  funnelProgressTrack: { height: 7, overflow: 'hidden', borderRadius: 4, backgroundColor: colors.border },
  funnelProgressFill: { height: 7, borderRadius: 4, backgroundColor: colors.primaryDeep },
  funnelConnector: { height: 24, flexDirection: 'row', alignItems: 'center', gap: 10 },
  funnelConnectorLine: { width: 2, height: 24, marginLeft: 10, backgroundColor: colors.primaryLight },
  funnelConversion: { overflow: 'hidden', borderRadius: 6, paddingHorizontal: 8, paddingVertical: 4, color: colors.primaryDeep, backgroundColor: colors.primaryLight, fontSize: 11, fontWeight: '800' },
  funnelFooter: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: colors.surface,
  },
  funnelFooterLabel: { color: colors.textMuted, fontSize: 13, fontWeight: '600' },
  funnelFooterValue: { color: colors.textMuted, fontSize: 16, fontWeight: '800' },
  funnelGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, paddingVertical: 6 },
  funnelGridItemWrap: { width: '48.5%' },
  funnelGridItem: {
    minHeight: 82,
    justifyContent: 'space-between',
    padding: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: colors.surface,
  },
  funnelPlaceholder: {
    alignSelf: 'flex-start',
    overflow: 'hidden',
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 3,
    color: colors.textMuted,
    backgroundColor: colors.surfaceSoft,
    fontSize: 11,
    fontWeight: '700',
  },
  group: { gap: 8 },
  groupTitle: { marginLeft: 4, color: colors.textMuted, fontSize: 12, fontWeight: '700' },
  groupBody: {
    overflow: 'hidden',
    marginHorizontal: -16,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  materialToolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  preparationRecommendationCard: {
    gap: 12,
    padding: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#DDD6FE',
    borderRadius: 12,
    backgroundColor: '#FAF9FF',
  },
  preparationRecommendationHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  preparationRecommendationIcon: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
    backgroundColor: '#EDE9FE',
  },
  preparationRecommendationTitle: { color: colors.text, fontSize: 15, lineHeight: 21, fontWeight: '800' },
  preparationRecommendationList: { gap: 9, paddingTop: 2 },
  preparationRecommendationRow: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 9,
    paddingVertical: 4,
  },
  preparationRecommendationDot: { width: 6, height: 6, marginTop: 7, borderRadius: 3, backgroundColor: '#8B5CF6' },
  preparationRecommendationActions: { flexDirection: 'row', gap: 10 },
  preparationRecommendationAction: {
    flex: 1,
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 9,
    backgroundColor: '#EDE9FE',
  },
  preparationRecommendationActionText: { color: '#6D28D9', fontSize: 14, lineHeight: 20, fontWeight: '800' },
  materialCard: {
    gap: 10,
    padding: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
  },
  materialCardImportant: { borderLeftWidth: 4, borderLeftColor: colors.warning },
  materialHeader: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  materialEditAction: { color: colors.primaryDeep, fontSize: 12, fontWeight: '800' },
  materialMeta: { marginTop: 3, color: colors.textMuted, fontSize: 12, lineHeight: 17 },
  materialBody: { color: colors.text, fontSize: 15, lineHeight: 23 },
  materialSortRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  materialTypeRow: { gap: 8, paddingVertical: 2 },
  iconButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: colors.surfaceSoft,
  },
  iconButtonText: { color: colors.primaryDeep, fontSize: 22, fontWeight: '800' },
  listRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    minHeight: 58,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  todoCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    minHeight: 70,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
  },
  todoCardCompact: { flexDirection: 'column', gap: 8 },
  processingPanel: { gap: 7 },
  processingTaskList: {
    overflow: 'hidden',
    marginHorizontal: -16,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  processingTaskRow: {
    minHeight: 62,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  processingTaskIcon: {
    width: 32,
    height: 32,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
    backgroundColor: '#EDF6F1',
  },
  processingTaskIconActive: { backgroundColor: '#F1EDFA' },
  processingTaskIconAttention: { backgroundColor: '#FCEEEE' },
  processingTaskTitle: { color: colors.text, fontSize: 14, lineHeight: 19, fontWeight: '800' },
  processingTaskDetail: { marginTop: 2, color: colors.textMuted, fontSize: 12, lineHeight: 17 },
  todoLegend: { flexDirection: 'row', flexWrap: 'wrap', gap: 14, paddingHorizontal: 16, paddingVertical: 9, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border, backgroundColor: colors.surface },
  todoLegendItem: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  todoLegendDot: { width: 7, height: 7, borderRadius: 4 },
  todoLegendDotHigh: { backgroundColor: colors.risk },
  todoLegendDotMedium: { backgroundColor: colors.warning },
  todoLegendDotLow: { backgroundColor: colors.success },
  todoLegendText: { color: colors.textMuted, fontSize: 11, fontWeight: '700' },
  todoTitleRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 8 },
  todoPriority: {
    minWidth: 28,
    overflow: 'hidden',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
    color: colors.primaryDeep,
    backgroundColor: colors.primaryLight,
    fontSize: 12,
    fontWeight: '900',
    textAlign: 'center',
  },
  todoAction: { color: colors.primaryDeep, fontSize: 12, fontWeight: '800' },
  todoActionButton: { flexShrink: 0, minWidth: 64, minHeight: 30, alignItems: 'center', justifyContent: 'center', borderRadius: 7, paddingHorizontal: 9, paddingVertical: 4, backgroundColor: colors.primaryLight },
  todoActionButtonCompact: { alignSelf: 'flex-end' },
  todoStatusTag: { alignSelf: 'flex-start', maxWidth: '100%', overflow: 'hidden', marginTop: 6, borderRadius: 6, paddingHorizontal: 7, paddingVertical: 3, color: colors.textMuted, backgroundColor: colors.surfaceSoft, fontSize: 11, lineHeight: 16, fontWeight: '700' },
  checkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    minHeight: 62,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  checkMark: { width: 26, minHeight: 24, alignItems: 'center', justifyContent: 'center' },
  checkMarkDone: { opacity: 1 },
  doneText: { color: colors.textMuted, textDecorationLine: 'line-through' },
  flexOne: { flex: 1, minWidth: 0 },
  rowTitle: { color: colors.text, fontSize: 15, fontWeight: '700', lineHeight: 21 },
  rowDetail: { color: colors.textMuted, fontSize: 13, lineHeight: 19, marginTop: 3 },
  chevron: { color: colors.primary, fontSize: 26 },
  jobRow: {
    gap: 7,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  jobListFocus: { color: colors.textMuted, fontSize: 12, lineHeight: 17 },
  jobRowHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  jobMetaStrip: {
    gap: 4,
    padding: 10,
    borderRadius: 14,
    backgroundColor: colors.surfaceSoft,
  },
  jobMetaText: { color: colors.textMuted, fontSize: 13, lineHeight: 18 },
  jobNextAction: { color: colors.text, fontSize: 14, fontWeight: '700', lineHeight: 20 },
  statusPill: { borderRadius: 999, paddingHorizontal: 9, paddingVertical: 5 },
  statusText: { fontSize: 12, fontWeight: '800' },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 2 },
  tagPill: {
    maxWidth: '100%',
    minHeight: 28,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 5,
    backgroundColor: colors.primaryLight,
  },
  tagText: {
    color: colors.primaryDeep,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  subtlePill: {
    minHeight: 28,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 5,
    backgroundColor: colors.surfaceSoft,
  },
  subtlePillText: { color: colors.textMuted, fontSize: 12, fontWeight: '700', lineHeight: 16 },
  chipScroller: { marginHorizontal: -16, paddingHorizontal: 16 },
  filterRow: { flexDirection: 'row', gap: 8, paddingRight: 16 },
  filterRowWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  filterChip: {
    minHeight: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 12,
    backgroundColor: colors.surface,
  },
  filterChipActive: { borderColor: colors.primaryDeep, backgroundColor: colors.primaryDeep },
  filterChipText: { color: colors.text, fontSize: 13, fontWeight: '800' },
  filterChipTextActive: { color: colors.surface },
  segmentedTabs: {
    flexDirection: 'row',
    gap: 3,
    padding: 3,
    borderRadius: 10,
    backgroundColor: '#ECEFED',
  },
  segmentedTab: {
    flex: 1,
    minWidth: 0,
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    paddingHorizontal: 5,
  },
  segmentedTabActive: {
    backgroundColor: colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    ...softShadow,
  },
  segmentedTabText: { maxWidth: '100%', color: colors.textMuted, fontSize: 13, fontWeight: '800', textAlign: 'center' },
  segmentedTabTextActive: { color: colors.text },
  interviewChip: {
    width: 172,
    marginRight: 10,
    padding: 14,
    borderRadius: 12,
    backgroundColor: colors.surface,
    ...softShadow,
  },
  interviewChipActive: { backgroundColor: colors.primaryLight },
  chipTitle: { color: colors.text, fontSize: 15, fontWeight: '800' },
  chipDetail: { marginTop: 4, color: colors.textMuted, fontSize: 12 },
  interviewListCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    minHeight: 72,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
  },
  interviewListCardActive: {
    backgroundColor: colors.surfaceSoft,
  },
  interviewListTools: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  interviewListSearch: { flex: 1, minWidth: 0 },
  interviewFilterToolbar: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  interviewFilterScroll: { flex: 1, minWidth: 0 },
  interviewFilterScroller: { gap: 8, paddingRight: 4 },
  interviewListRow: {
    minHeight: 84,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 11,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
  },
  interviewListRowActive: { backgroundColor: '#F7F8F7' },
  interviewListState: { overflow: 'hidden', borderRadius: 6, paddingHorizontal: 7, paddingVertical: 4, fontSize: 11, fontWeight: '800' },
  interviewListStateUpcoming: { color: '#84662F', backgroundColor: colors.warningLight },
  interviewListStateReview: { color: '#765D82', backgroundColor: '#EFE8F2' },
  interviewListStateFeedback: { color: '#4F735E', backgroundColor: colors.successLight },
  interviewListCopy: { minWidth: 0, flex: 1, gap: 2 },
  interviewListTitleRow: { minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 8 },
  interviewListRole: { color: colors.text, fontSize: 13, lineHeight: 19, fontWeight: '700' },
  interviewRoundTag: { flexShrink: 0, maxWidth: 96, overflow: 'hidden', borderRadius: 6, paddingHorizontal: 7, paddingVertical: 3, color: '#1D4ED8', backgroundColor: '#EFF6FF', fontSize: 11, fontWeight: '800' },
  mockInterviewBanner: { minHeight: 88, flexDirection: 'row', alignItems: 'center', gap: 12, padding: 16, borderWidth: 1, borderStyle: 'dashed', borderColor: '#C4B5FD', borderRadius: 12, backgroundColor: '#F5F3FF', ...softShadow },
  mockInterviewGlyph: { width: 36, color: '#7C3AED', fontSize: 26, textAlign: 'center' },
  mockInterviewTitle: { color: colors.text, fontSize: 16, lineHeight: 22, fontWeight: '800' },
  mockInterviewDetail: { marginTop: 3, color: colors.textMuted, fontSize: 12, lineHeight: 17 },
  mockInterviewAction: { color: '#7C3AED', fontSize: 12, fontWeight: '800' },
  detailHeader: { gap: 10, padding: 18, borderRadius: 8, backgroundColor: colors.surface },
  detailSummary: { gap: 5, paddingTop: 8, paddingBottom: 8 },
  detailSubject: { color: colors.text, fontSize: 22, fontWeight: '800', lineHeight: 29 },
  aiReviewEmptyTitle: { alignSelf: 'stretch', color: colors.text, fontSize: 18, fontWeight: '800', lineHeight: 26 },
  detailMetaLine: { marginTop: 4, color: colors.text, fontSize: 14, lineHeight: 20, fontWeight: '700' },
  detailState: { overflow: 'hidden', borderRadius: 6, paddingHorizontal: 8, paddingVertical: 5, color: colors.primaryDeep, backgroundColor: colors.primaryLight, fontSize: 12, fontWeight: '800' },
  attributeGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  attributeCell: { width: '48.5%', minHeight: 68, justifyContent: 'space-between', gap: 5, padding: 11, borderWidth: StyleSheet.hairlineWidth, borderColor: colors.border, borderRadius: 8, backgroundColor: colors.surface },
  attributeValue: { color: colors.text, fontSize: 14, lineHeight: 19, fontWeight: '700' },
  detailMoreButton: {
    width: 36,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: colors.surfaceSoft,
  },
  linkedJobInline: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 4,
    paddingVertical: 8,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
  },
  linkedJobInlineText: { minWidth: 0, flex: 1, color: colors.text, fontSize: 13, lineHeight: 18, fontWeight: '700' },
  linkedJobInlineAction: { flexShrink: 0, color: colors.textMuted, fontSize: 12, lineHeight: 17, fontWeight: '700' },
  detailMoreGlyph: { color: colors.primaryDeep, fontSize: 15, fontWeight: '900', lineHeight: 16 },
  interviewSettingsPanel: {
    gap: 12,
    padding: 16,
    marginHorizontal: -16,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  settingsDeleteRow: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
  },
  settingsStatusRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  settingsStatusOption: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 2,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  settingsStatusCheck: { width: 24, color: colors.primaryDeep, fontSize: 16, fontWeight: '900', textAlign: 'center' },
  sectionBody: { gap: 10, padding: 16 },
  sourceAttachment: { minHeight: 66, flexDirection: 'row', alignItems: 'center', gap: 12, padding: 14, backgroundColor: colors.surface },
  sourceAttachmentGlyph: { width: 32, color: colors.primaryDeep, fontSize: 22, textAlign: 'center' },
  offerEmptyState: { minHeight: 260, alignItems: 'center', justifyContent: 'center', gap: 12, padding: 28, borderRadius: 12, backgroundColor: colors.surface },
  offerEmptyGlyph: { color: colors.primary, fontSize: 42, lineHeight: 48 },
  paragraph: { color: colors.text, fontSize: 15, lineHeight: 22 },
  preparationProgressCard: {
    gap: 8,
    padding: 12,
    borderRadius: 8,
    backgroundColor: colors.primaryLight,
  },
  preparationMainSection: { gap: 12, paddingVertical: 4 },
  preparationProgressLayout: { flexDirection: 'row', alignItems: 'center', gap: 13 },
  preparationProgressRing: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center', borderWidth: 4, borderColor: colors.primaryDeep, borderRadius: 24, backgroundColor: colors.surface },
  preparationProgressPercent: { color: colors.primaryDeep, fontSize: 13, fontWeight: '900', fontVariant: ['tabular-nums'] },
  preparationProgressHeader: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  preparationProgressTitle: { flex: 1, minWidth: 0, color: colors.text, fontSize: 15, fontWeight: '700', lineHeight: 21 },
  preparationProgressValue: { flexShrink: 0, minWidth: 42, color: colors.primaryDeep, fontSize: 13, lineHeight: 20, fontWeight: '900', textAlign: 'right', fontVariant: ['tabular-nums'] },
  preparationProgressTrack: { height: 5, overflow: 'hidden', borderRadius: 3, backgroundColor: colors.surface },
  preparationProgressFill: { height: '100%', borderRadius: 3, backgroundColor: colors.primaryDeep },
  preparationSectionHeader: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inlineEditButton: {
    minWidth: 50,
    minHeight: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    paddingHorizontal: 12,
    backgroundColor: colors.surfaceSoft,
  },
  inlineEditButtonText: { color: colors.primaryDeep, fontSize: 13, fontWeight: '800' },
  preparationEditor: { gap: 14, paddingVertical: 8 },
  preparationReading: { gap: 0, overflow: 'hidden', borderWidth: StyleSheet.hairlineWidth, borderColor: colors.border, borderRadius: 8 },
  preparationReadingBlock: { gap: 8, padding: 16, backgroundColor: colors.surface },
  preparationSubheading: { color: colors.primaryDeep, fontSize: 13, fontWeight: '900' },
  preparationChecklist: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.border },
  compactCheckRow: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
  },
  twoColumnFields: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  recorderPanel: {
    alignItems: 'center',
    gap: 16,
    padding: 18,
    borderRadius: 12,
    backgroundColor: colors.surface,
    ...softShadow,
  },
  recordCircle: {
    width: 154,
    height: 154,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 77,
    backgroundColor: colors.surfaceSoft,
  },
  recordCircleActive: { backgroundColor: colors.riskLight },
  recordDuration: { color: colors.text, fontSize: 31, fontWeight: '800' },
  recordLabel: { marginTop: 5, color: colors.textMuted, fontSize: 13, fontWeight: '700' },
  recorderHint: { color: colors.textMuted, fontSize: 13, lineHeight: 19, textAlign: 'center' },
  recordingWorkspace: { gap: 12 },
  recordingStage: { minHeight: 330, alignItems: 'center', justifyContent: 'center', gap: 10, padding: 22, borderRadius: 12, backgroundColor: colors.surface },
  recordingStageActive: { backgroundColor: '#FFFBFA' },
  recordingStageTitle: { color: colors.text, fontSize: 28, lineHeight: 36, fontWeight: '800', fontVariant: ['tabular-nums'] },
  recordingStageMeta: { color: colors.textMuted, fontSize: 13, lineHeight: 19 },
  recordingSafetyRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: 10 },
  recordingSafetyText: { color: colors.textMuted, fontSize: 11, lineHeight: 16, fontVariant: ['tabular-nums'] },
  transcriptionTaskPanel: { overflow: 'hidden', borderWidth: StyleSheet.hairlineWidth, borderColor: colors.border, borderRadius: 10, backgroundColor: colors.surface },
  transcriptionTaskHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 14, paddingVertical: 10, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border },
  transcriptionTaskRow: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 14, paddingVertical: 9, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border },
  transcriptionTaskDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#1D4ED8' },
  transcriptionTaskDotFailed: { backgroundColor: '#B45353' },
  audioDiagnosticRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 9, padding: 11, borderRadius: 8, backgroundColor: colors.surfaceSoft },
  audioDiagnosticDot: { width: 8, height: 8, marginTop: 6, borderRadius: 4, backgroundColor: '#047857' },
  audioDiagnosticDotWarning: { backgroundColor: '#B7791F' },
  audioDiagnosticDotInvalid: { backgroundColor: '#B45353' },
  audioDiagnosticTitle: { color: colors.text, fontSize: 13, lineHeight: 18, fontWeight: '800' },
  audioAuditRow: { flexDirection: 'row', gap: 8 },
  audioAuditButton: { flex: 1, minHeight: 38, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, borderRadius: 8, backgroundColor: colors.surfaceSoft },
  audioAuditButtonText: { color: colors.text, fontSize: 12, lineHeight: 17, fontWeight: '700' },
  transcriptionErrorBox: { gap: 3, padding: 11, borderRadius: 8, backgroundColor: '#FFF7ED' },
  transcriptionErrorTitle: { color: '#9A3412', fontSize: 13, lineHeight: 18, fontWeight: '800' },
  recordingWaveform: { height: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5 },
  recordingWaveBar: { width: 4, minHeight: 8, borderRadius: 2, backgroundColor: '#D1D5DB' },
  recordingWaveBarActive: { backgroundColor: colors.risk },
  recordMainControlShell: { width: 142, height: 142, alignItems: 'center', justifyContent: 'center', marginVertical: 4 },
  recordPulseRing: { position: 'absolute', width: 142, height: 142, borderWidth: 2, borderColor: '#E6C8C1', borderRadius: 71, backgroundColor: '#FBEEEB' },
  recordMainControl: { width: 112, height: 112, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: '#E6C8C1', borderRadius: 56, backgroundColor: colors.riskLight },
  recordMainControlActive: { borderColor: colors.risk, backgroundColor: '#F9E9E5' },
  recordMainControlCore: { width: 78, height: 78, alignItems: 'center', justifyContent: 'center', borderRadius: 39, backgroundColor: colors.surface },
  recordMainControlCoreActive: { backgroundColor: colors.risk },
  recordingAuxiliaryActions: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: 8 },
  markerButton: { minHeight: 36, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, borderRadius: 8, paddingHorizontal: 12, backgroundColor: colors.surfaceSoft },
  markerButtonText: { color: colors.primaryDeep, fontSize: 12, fontWeight: '800' },
  recordImportAction: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 },
  recordImportActionText: { color: colors.primaryDeep, fontSize: 13, fontWeight: '800' },
  permissionStrip: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: colors.warningLight,
  },
  permissionStripCopy: { flex: 1, gap: 2 },
  permissionAction: {
    minWidth: 54,
    minHeight: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: colors.surface,
  },
  permissionActionText: { color: colors.primaryDeep, fontSize: 13, fontWeight: '800' },
  recordingCompactCard: {
    minHeight: 82,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: colors.surface,
  },
  recordingCompactCardActive: { borderColor: '#D9B5AE', backgroundColor: '#FFFBFA' },
  recordingStatusDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.primary },
  recordingStatusDotActive: { backgroundColor: colors.risk },
  recordingCompactCopy: { flex: 1, gap: 4 },
  recordingCompactTitle: { color: colors.text, fontSize: 17, fontWeight: '800' },
  recordingCompactMeta: { color: colors.textMuted, fontSize: 13, lineHeight: 18 },
  recordingCompactMetaWarning: { color: colors.risk, fontWeight: '700' },
  recordControl: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 24,
    backgroundColor: colors.riskLight,
  },
  recordControlActive: { backgroundColor: colors.risk },
  recordControlGlyph: { color: colors.risk, fontSize: 22, lineHeight: 24 },
  recordControlGlyphActive: { color: colors.surface, fontSize: 15 },
  recordUtilityRow: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
    borderRadius: 8,
    backgroundColor: colors.surfaceSoft,
  },
  recordUtilityGlyph: { width: 20, color: colors.primaryDeep, fontSize: 18, fontWeight: '700', textAlign: 'center' },
  recordUtilityText: { flex: 1, color: colors.text, fontSize: 14, fontWeight: '700' },
  actionRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: 10 },
  jobActionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 2 },
  quickActionGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  inlineActionGrid: { flexDirection: 'row', gap: 10 },
  inlineActionTile: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minHeight: 62,
    justifyContent: 'flex-start',
    padding: 12,
    borderRadius: 12,
    backgroundColor: colors.surface,
    ...softShadow,
  },
  quickAction: {
    width: '48.5%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minHeight: 70,
    justifyContent: 'flex-start',
    padding: 14,
    borderRadius: 12,
    backgroundColor: colors.surfaceSoft,
  },
  actionGlyph: { width: 24, color: colors.primaryDeep, fontSize: 18, fontWeight: '900', textAlign: 'center' },
  quickActionTitle: { color: colors.text, fontSize: 15, fontWeight: '800', lineHeight: 20 },
  quickActionDetail: { color: colors.textMuted, fontSize: 12, lineHeight: 17 },
  compactActionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, padding: 14 },
  collapsibleHeader: {
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
  },
  expandIndicator: { color: colors.primaryDeep, fontSize: 13, fontWeight: '800' },
  resultButton: {
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    paddingHorizontal: 12,
    backgroundColor: colors.surfaceSoft,
  },
  resultButtonActive: { backgroundColor: colors.successLight },
  resultButtonText: { color: colors.text, fontSize: 13, fontWeight: '800' },
  resultButtonTextActive: { color: '#4F6F5E' },
  reviewResultControl: { flexDirection: 'row', gap: 4, padding: 4, backgroundColor: colors.surfaceSoft },
  reviewResultControlCompact: { flexWrap: 'wrap' },
  reviewResultOption: { flex: 1, minHeight: 38, alignItems: 'center', justifyContent: 'center', borderRadius: 6, paddingHorizontal: 4 },
  reviewResultOptionCompact: { flexGrow: 0, flexShrink: 0, flexBasis: '49%' },
  reviewResultOptionActive: { backgroundColor: colors.surface, borderWidth: StyleSheet.hairlineWidth, borderColor: colors.border },
  reviewResultText: { color: colors.textMuted, fontSize: 11, fontWeight: '700', textAlign: 'center' },
  reviewResultTextActive: { color: colors.text, fontWeight: '800' },
  aiReviewEmptyCard: { minHeight: 132, alignItems: 'flex-start', justifyContent: 'center', gap: 7, padding: 18, borderWidth: 1, borderStyle: 'dashed', borderColor: '#C4B5FD', borderRadius: 12, backgroundColor: '#F7F5FF' },
  aiReviewGlyph: { color: colors.primaryDeep, fontSize: 28, lineHeight: 34 },
  aiReviewLoadingCard: { minHeight: 132, justifyContent: 'center', gap: 12, padding: 18, borderWidth: 1, borderColor: '#DDD6FE', borderRadius: 12, backgroundColor: '#F7F5FF' },
  aiReviewLoadingHeader: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 4 },
  reviewErrorScroll: { maxHeight: 128 },
  aiSkeletonWide: { width: '100%', height: 12, borderRadius: 6, backgroundColor: '#C4B5FD' },
  aiSkeletonMedium: { width: '78%', height: 12, borderRadius: 6, backgroundColor: '#DDD6FE' },
  aiSkeletonShort: { width: '56%', height: 12, borderRadius: 6, backgroundColor: '#EDE9FE' },
  reviewEditor: { gap: 8, padding: 14, borderWidth: StyleSheet.hairlineWidth, borderColor: colors.border, borderRadius: 8, backgroundColor: colors.surface },
  characterCount: { marginTop: -6, color: colors.textMuted, fontSize: 11, textAlign: 'right' },
  primaryButton: {
    minHeight: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    borderRadius: 10,
    paddingHorizontal: 16,
    backgroundColor: colors.primaryDeep,
  },
  primaryButtonText: { color: colors.surface, fontSize: 15, fontWeight: '800' },
  buttonDisabled: { opacity: 0.55 },
  secondaryButton: {
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    paddingHorizontal: 16,
    backgroundColor: colors.surfaceSoft,
  },
  secondaryButtonText: { color: colors.text, fontSize: 15, fontWeight: '800' },
  destructiveButton: {
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    paddingHorizontal: 16,
    backgroundColor: colors.riskLight,
  },
  destructiveButtonText: { color: colors.risk, fontSize: 15, fontWeight: '800' },
  savedAudioBox: { width: '100%', gap: 10, padding: 14, borderRadius: 12, backgroundColor: colors.surfaceSoft },
  savedAudioCard: {
    gap: 14,
    padding: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: colors.surface,
  },
  savedAudioHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  savedAudioHeaderCopy: { flex: 1, gap: 3 },
  savedAudioName: { color: colors.textMuted, fontSize: 12, lineHeight: 17 },
  audioStateLabel: { color: colors.primary, fontSize: 11, fontWeight: '800' },
  playbackRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    width: '100%',
    padding: 12,
    borderRadius: 12,
    backgroundColor: colors.surface,
  },
  playbackTimeline: { flex: 1, gap: 2 },
  playbackTimes: { flexDirection: 'row', justifyContent: 'space-between' },
  playbackTimeText: { minWidth: 52, color: colors.textMuted, fontSize: 11 },
  playbackTimeEnd: { textAlign: 'right' },
  audioScrubberHitbox: { height: 28, justifyContent: 'center' },
  audioScrubberTrack: { height: 4, borderRadius: 2, backgroundColor: colors.border },
  audioScrubberFill: { position: 'absolute', top: 0, bottom: 0, left: 0, borderRadius: 2, backgroundColor: colors.primaryDeep },
  audioScrubberThumb: {
    position: 'absolute',
    top: -5,
    width: 14,
    height: 14,
    marginLeft: -7,
    borderWidth: 2,
    borderColor: colors.surface,
    borderRadius: 7,
    backgroundColor: colors.primaryDeep,
  },
  playbackMeta: { flex: 1, gap: 2 },
  playbackButton: {
    width: 42,
    minWidth: 42,
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 21,
    backgroundColor: colors.primaryDeep,
  },
  playbackButtonText: { color: colors.surface, fontSize: 13, fontWeight: '800' },
  markerSummary: { color: colors.textMuted, fontSize: 12, lineHeight: 18 },
  audioPrimaryActions: { flexDirection: 'row', gap: 10 },
  audioSecondaryAction: {
    flex: 1,
    minHeight: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: colors.surfaceSoft,
  },
  audioPrimaryAction: {
    flex: 1,
    minHeight: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: colors.primaryDeep,
  },
  audioTextActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 20, paddingHorizontal: 2 },
  audioTextAction: { color: colors.textMuted, fontSize: 13, fontWeight: '700' },
  audioDeleteAction: { color: colors.risk, fontSize: 13, fontWeight: '700' },
  reviewPlayer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    minHeight: 56,
    paddingHorizontal: 12,
    paddingTop: 5,
    paddingBottom: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  persistentReviewPlayer: {
    position: 'absolute',
    right: 12,
    bottom: 12,
    left: 12,
    zIndex: 18,
    minHeight: 72,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#DED5F2',
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.98)',
    ...softShadow,
  },
  persistentReviewPlayerError: { borderColor: '#E8C9C5', backgroundColor: '#FFF8F7' },
  persistentReviewPlayButton: {
    width: 40,
    minHeight: 40,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    backgroundColor: '#5E4A8A',
  },
  persistentReviewPlayButtonDisabled: { backgroundColor: '#A9A3B3' },
  persistentReviewPlayerBody: { flex: 1, minWidth: 0, gap: 2 },
  persistentReviewPlayerHeader: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  persistentReviewPlayerTitle: { flex: 1, flexShrink: 1, color: colors.text, fontSize: 12, lineHeight: 17, fontWeight: '800' },
  persistentReviewPlayerTime: { flexShrink: 0, minWidth: 74, color: colors.textMuted, fontSize: 9, textAlign: 'right', fontVariant: ['tabular-nums'] },
  recordDocumentPanel: {
    overflow: 'hidden',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: colors.surface,
    ...softShadow,
  },
  recordDocumentHeader: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: colors.surface,
  },
  recordDocumentIcon: { width: 32, height: 32, alignItems: 'center', justifyContent: 'center', borderRadius: 8, backgroundColor: '#F1EDFA' },
  recordDocumentTitle: { color: colors.text, fontSize: 14, lineHeight: 19, fontWeight: '800' },
  recordDocumentMeta: { marginTop: 1, color: colors.textMuted, fontSize: 11, lineHeight: 16 },
  recordDocumentAction: { minHeight: 34, flexDirection: 'row', alignItems: 'center', gap: 5, borderRadius: 8, paddingHorizontal: 9, backgroundColor: '#F5F3FF' },
  recordDocumentActionText: { color: '#5E4A8A', fontSize: 12, fontWeight: '800' },
  reviewContentToolbar: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  reviewContentSwitch: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    gap: 4,
    padding: 4,
    borderRadius: 10,
    backgroundColor: '#ECEFED',
  },
  reviewContentSwitchItem: {
    flex: 1,
    minWidth: 0,
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    paddingHorizontal: 8,
  },
  reviewContentSwitchItemActive: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    ...softShadow,
  },
  reviewContentSwitchLabel: { color: colors.textMuted, fontSize: 14, fontWeight: '700' },
  reviewContentSwitchLabelActive: { color: colors.text, fontWeight: '800' },
  reviewExportButton: { width: 46, minHeight: 46, alignItems: 'center', justifyContent: 'center', borderRadius: 10, backgroundColor: '#F5F3FF' },
  reviewResultSection: { gap: 8, paddingTop: 2 },
  reviewSectionHeading: { minHeight: 24, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  reviewResultCurrent: { flexShrink: 0, color: colors.textMuted, fontSize: 11, fontWeight: '700' },
  transcriptDocumentSection: { gap: 10, paddingTop: 2 },
  transcriptSectionTitle: { flex: 1, minWidth: 0, color: colors.text, fontSize: 16, lineHeight: 22, fontWeight: '800' },
  transcriptSectionCount: { flexShrink: 0, color: colors.textMuted, fontSize: 11, fontWeight: '700' },
  transcriptHeadingActions: { flexShrink: 0, flexDirection: 'row', alignItems: 'center', gap: 7 },
  transcriptLoadMore: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 9 },
  transcriptLoadMoreText: { color: colors.textMuted, fontSize: 12, fontWeight: '800' },
  transcriptEmptyDocument: {
    minHeight: 180,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 28,
    paddingVertical: 24,
  },
  transcriptOverview: { gap: 4, paddingVertical: 4 },
  transcriptTools: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  transcriptSearchBox: { flex: 1, minHeight: 42, flexDirection: 'row', alignItems: 'center', gap: 8, borderWidth: 1, borderColor: colors.border, borderRadius: 9, paddingHorizontal: 11, backgroundColor: colors.surface },
  transcriptSearchInput: { flex: 1, minWidth: 0, paddingVertical: 8, color: colors.text, fontSize: 14 },
  transcriptToolButton: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center', borderRadius: 9, backgroundColor: colors.surface },
  reviewDeleteAction: { minHeight: 40, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 },
  reviewSubsection: { gap: 8, paddingTop: 4 },
  reviewScoreGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, padding: 12, backgroundColor: colors.surface },
  reviewScoreItem: { width: '48.5%', minHeight: 72, justifyContent: 'center', gap: 3, padding: 12, borderRadius: 9, backgroundColor: '#F9FAFB' },
  reviewScoreValue: { color: '#4F46E5', fontSize: 20, fontWeight: '800' },
  reviewScoreLabel: { color: colors.textMuted, fontSize: 12, fontWeight: '700' },
  reviewScoreSheetSummary: { alignItems: 'center', gap: 2, paddingVertical: 8 },
  reviewScoreSheetValue: { color: '#4F46E5', fontSize: 34, lineHeight: 42, fontWeight: '800', fontVariant: ['tabular-nums'] },
  reviewScoreSheetScale: { color: colors.textMuted, fontSize: 12, lineHeight: 18, fontWeight: '600' },
  reviewScoreSheetList: { overflow: 'hidden', borderWidth: StyleSheet.hairlineWidth, borderColor: colors.border, borderRadius: 10, backgroundColor: colors.surface },
  reviewScoreSheetRow: { gap: 9, paddingHorizontal: 14, paddingVertical: 13, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border },
  reviewScoreSheetHeader: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  reviewScoreSheetNumber: { flexShrink: 0, minWidth: 42, color: '#4F46E5', fontSize: 13, lineHeight: 20, fontWeight: '800', textAlign: 'right', fontVariant: ['tabular-nums'] },
  reviewScoreTrack: { height: 5, overflow: 'hidden', borderRadius: 3, backgroundColor: '#ECEEF0' },
  reviewScoreFill: { height: '100%', borderRadius: 3, backgroundColor: '#7C6FA3' },
  questionReviewCard: { gap: 8, padding: 14, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border, backgroundColor: colors.surface },
  questionReviewHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 8 },
  questionReviewIndex: { color: '#6D28D9', fontSize: 12, fontWeight: '900' },
  questionReviewTitle: { flex: 1, minWidth: 0, color: colors.text, fontSize: 14, lineHeight: 20, fontWeight: '700' },
  questionReviewScore: { flexShrink: 0, minWidth: 30, color: '#4F46E5', fontSize: 12, lineHeight: 20, fontWeight: '900', textAlign: 'right', fontVariant: ['tabular-nums'] },
  questionReviewFeedback: { padding: 10, borderRadius: 8, color: '#1D4ED8', backgroundColor: '#EFF6FF', fontSize: 13, lineHeight: 19 },
  evidenceButton: { alignSelf: 'flex-start', minHeight: 32, justifyContent: 'center', borderRadius: 7, paddingHorizontal: 9, backgroundColor: '#F3F4F6' },
  evidenceButtonText: { color: colors.textMuted, fontSize: 11, fontWeight: '800' },
  reviewActionRow: { minHeight: 54, flexDirection: 'row', alignItems: 'flex-start', gap: 9, paddingHorizontal: 14, paddingVertical: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border, backgroundColor: colors.surface },
  reviewActionAdd: { flexShrink: 0, minHeight: 30, justifyContent: 'center', borderRadius: 7, paddingHorizontal: 9, backgroundColor: '#EEF2FF' },
  reviewActionAddDone: { backgroundColor: '#F3F4F6' },
  reviewActionAddText: { color: '#4F46E5', fontSize: 11, fontWeight: '800' },
  reviewActionAddTextDone: { color: colors.textMuted },
  keywordRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, paddingBottom: 8 },
  keywordTag: {
    overflow: 'hidden',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    color: colors.primaryDeep,
    backgroundColor: colors.primaryLight,
    fontSize: 11,
    fontWeight: '800',
  },
  questionIndexRow: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
  },
  questionIndexNumber: { width: 28, color: colors.primaryDeep, fontSize: 12, fontWeight: '900' },
  questionIndexText: { flex: 1, color: colors.text, fontSize: 14, lineHeight: 20, fontWeight: '700' },
  questionIndexTime: { color: colors.textMuted, fontSize: 11, fontVariant: ['tabular-nums'] },
  transcriptSegment: {
    gap: 7,
    paddingHorizontal: 16,
    paddingVertical: 13,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
  },
  transcriptSegmentActive: { backgroundColor: '#FAF8FF' },
  transcriptSegmentHeader: { minHeight: 28, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  transcriptSegmentIdentity: { minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 7 },
  transcriptSegmentIndex: { minWidth: 22, height: 22, overflow: 'hidden', borderRadius: 11, color: '#5E4A8A', backgroundColor: '#F1EDFA', fontSize: 11, lineHeight: 22, fontWeight: '900', textAlign: 'center', fontVariant: ['tabular-nums'] },
  transcriptSegmentTools: { flexShrink: 0, flexDirection: 'row', alignItems: 'center', gap: 7 },
  transcriptSpeaker: { color: colors.primaryDeep, fontSize: 12, fontWeight: '900' },
  transcriptTimestamp: { color: colors.textMuted, fontSize: 11, fontVariant: ['tabular-nums'] },
  transcriptMiniWave: { height: 14, flexDirection: 'row', alignItems: 'center', gap: 2 },
  transcriptMiniWaveBar: { width: 2, borderRadius: 1, backgroundColor: '#B7A9D6' },
  transcriptCopyAction: { width: 30, minHeight: 28, alignItems: 'center', justifyContent: 'center' },
  transcriptHighlight: { color: colors.primaryDeep, fontWeight: '900', backgroundColor: colors.primaryLight },
  expandTranscript: { color: colors.primaryDeep, fontSize: 12, fontWeight: '800' },
  iconInputRow: {
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    backgroundColor: colors.surface,
  },
  iconTextAreaRow: {
    minHeight: 116,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingTop: 12,
    backgroundColor: colors.surface,
  },
  inputGlyph: { width: 20, color: colors.primary, fontSize: 17, textAlign: 'center' },
  iconTextInput: { flex: 1, minHeight: 44, color: colors.text, fontSize: 14 },
  iconTextArea: { flex: 1, minHeight: 100, color: colors.text, fontSize: 14, lineHeight: 21 },
  reminderPickerButton: { minHeight: 64, flexDirection: 'row', alignItems: 'center', gap: 11, borderWidth: StyleSheet.hairlineWidth, borderColor: colors.border, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 10, backgroundColor: colors.surface },
  followUpComposer: { gap: 10, padding: 14, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border, backgroundColor: colors.surface },
  followUpInput: { minHeight: 92, borderWidth: 1, borderColor: colors.border, borderRadius: 8, padding: 12, color: colors.text, backgroundColor: colors.surface, fontSize: 14, lineHeight: 21 },
  followUpAddButton: { alignSelf: 'flex-end', minHeight: 38, alignItems: 'center', justifyContent: 'center', borderRadius: 8, paddingHorizontal: 14, backgroundColor: colors.primaryDeep },
  followUpTimelineItem: { minHeight: 64, flexDirection: 'row', alignItems: 'flex-start', gap: 12, padding: 14, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border, backgroundColor: colors.surface },
  followUpDot: { width: 8, height: 8, marginTop: 7, borderRadius: 4, backgroundColor: colors.primary },
  textArea: { minHeight: 190, padding: 16, color: colors.text, fontSize: 15, lineHeight: 22 },
  noteArea: { minHeight: 110, padding: 14, borderWidth: 1, borderColor: colors.border, borderRadius: 8, color: colors.text, backgroundColor: colors.surface, fontSize: 15, lineHeight: 22 },
  longNoteArea: { minHeight: 180, padding: 14, borderWidth: 1, borderColor: colors.border, borderRadius: 8, color: colors.text, backgroundColor: colors.surface, fontSize: 15, lineHeight: 22 },
  reviewBlock: {
    gap: 7,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderLeftWidth: 3,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderLeftColor: '#D1D5DB',
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
  },
  reviewBlockSuccess: { borderLeftColor: '#6FA58A', backgroundColor: '#FAFDFC' },
  reviewBlockRisk: { borderLeftColor: '#C98D83', backgroundColor: '#FEFCFC' },
  reviewBlockAction: { borderLeftColor: '#7C8FB7', backgroundColor: '#FAFBFD' },
  stateBanner: {
    width: '100%',
    padding: 12,
    borderRadius: 14,
    backgroundColor: colors.primaryLight,
  },
  stateBannerText: { color: colors.primaryDeep, fontSize: 13, fontWeight: '700', lineHeight: 18 },
  importBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 16,
    borderRadius: 12,
    backgroundColor: colors.surface,
    ...softShadow,
  },
  filterEntry: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    minHeight: 58,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: colors.surface,
    ...softShadow,
  },
  tabBar: {
    position: 'absolute',
    right: 12,
    bottom: 12,
    left: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 6,
    padding: 6,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.96)',
    ...softShadow,
  },
  tabButton: { flex: 1, alignItems: 'center', gap: 2, paddingVertical: 6, borderRadius: 10 },
  tabButtonActive: { backgroundColor: colors.primaryLight },
  tabIcon: { color: colors.textMuted, fontSize: 18, lineHeight: 20 },
  tabText: { color: colors.textMuted, fontSize: 11, fontWeight: '700' },
  tabTextActive: { color: colors.primaryDeep },
  ocrTaskBanner: {
    position: 'absolute',
    right: 18,
    bottom: 94,
    left: 18,
    zIndex: 20,
    minHeight: 62,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.98)',
    ...softShadow,
  },
  ocrTaskBannerNested: { bottom: 18 },
  floatingBannerAbovePlayer: { bottom: 96 },
  ocrTaskBannerError: { borderColor: '#E8C9C5', backgroundColor: '#FFF8F7' },
  ocrTaskIcon: { width: 34, minHeight: 34, alignItems: 'center', justifyContent: 'center', borderRadius: 8, backgroundColor: colors.primaryLight },
  ocrTaskIconError: { backgroundColor: '#F7E7E4' },
  ocrTaskTitle: { color: colors.text, fontSize: 14, lineHeight: 20, fontWeight: '800' },
  ocrTaskDetail: { marginTop: 1, color: colors.textMuted, fontSize: 12, lineHeight: 17 },
  importNoticeBanner: {
    position: 'absolute',
    right: 18,
    bottom: 94,
    left: 18,
    zIndex: 22,
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#CDE7DC',
    borderRadius: 12,
    backgroundColor: '#F3FBF7',
    ...softShadow,
  },
  importNoticeIcon: { width: 30, minHeight: 30, alignItems: 'center', justifyContent: 'center', borderRadius: 8, backgroundColor: '#E2F5EB' },
  importNoticeText: { flex: 1, color: '#285847', fontSize: 13, lineHeight: 19, fontWeight: '800' },
  sheetBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.32)' },
  sheet: {
    maxHeight: '92%',
    gap: 14,
    padding: 20,
    paddingBottom: 32,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    backgroundColor: colors.surface,
  },
  sheetContent: { gap: 14 },
  sheetScrollContent: { gap: 14, paddingBottom: 4 },
  sheetTitle: { color: colors.text, fontSize: 22, fontWeight: '800' },
  sheetHandle: { alignSelf: 'center', width: 38, height: 4, borderRadius: 2, backgroundColor: colors.border },
  sheetHeaderRow: { minHeight: 42, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  sheetCloseButton: { width: 40, minHeight: 40, alignItems: 'center', justifyContent: 'center', borderRadius: 20, backgroundColor: colors.surfaceSoft },
  formPage: { gap: 14, paddingBottom: 28 },
  formSectionTitle: { color: colors.text, fontSize: 16, fontWeight: '800' },
  collapsibleFormSection: { overflow: 'hidden', borderWidth: StyleSheet.hairlineWidth, borderColor: colors.border, borderRadius: 8, backgroundColor: colors.surface },
  collapsibleFormHeader: { minHeight: 50, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, paddingHorizontal: 14, paddingVertical: 10 },
  collapsibleFormAction: { color: colors.primary, fontSize: 12, fontWeight: '800' },
  collapsibleFormBody: { gap: 14, paddingHorizontal: 14, paddingBottom: 16, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.border },
  formField: { gap: 7 },
  formLabel: { color: colors.text, fontSize: 13, fontWeight: '700' },
  formInput: {
    minHeight: 44,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: 14,
    color: colors.text,
    backgroundColor: colors.surface,
    fontSize: 15,
  },
  formPickerButton: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, borderWidth: 1, borderColor: colors.border, borderRadius: 8, paddingHorizontal: 14, paddingVertical: 10, backgroundColor: colors.surface },
  formPickerValue: { flex: 1, color: colors.text, fontSize: 15 },
  formPickerPlaceholder: { flex: 1, color: colors.textMuted, fontSize: 15 },
  searchInput: {
    flex: 1,
    minHeight: 44,
    borderRadius: 8,
    paddingHorizontal: 14,
    color: colors.text,
    backgroundColor: colors.surface,
    fontSize: 15,
  },
  searchToolbar: { flexDirection: 'row', alignItems: 'stretch', gap: 8 },
  searchToolButton: { width: 44, minHeight: 44, alignItems: 'center', justifyContent: 'center', borderWidth: StyleSheet.hairlineWidth, borderColor: colors.border, borderRadius: 8, backgroundColor: colors.surface },
  searchToolGlyph: { color: colors.primaryDeep, fontSize: 19, fontWeight: '800' },
  researchTaskBanner: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 14, paddingVertical: 10, borderWidth: StyleSheet.hairlineWidth, borderColor: '#DDD3F5', borderRadius: 8, backgroundColor: '#F7F4FF' },
  researchTaskTitle: { color: '#5B3B91', fontSize: 13, lineHeight: 18, fontWeight: '800' },
  researchTaskDetail: { marginTop: 2, color: colors.textMuted, fontSize: 12, lineHeight: 17 },
  researchProgressPanel: { gap: 4, padding: 13, borderWidth: StyleSheet.hairlineWidth, borderColor: '#DDD3F5', borderRadius: 8, backgroundColor: '#F7F4FF' },
  batchSelectionActions: { minHeight: 40, flexDirection: 'row', alignItems: 'center', gap: 8 },
  batchResearchList: { maxHeight: 360 },
  batchResearchRow: { minHeight: 62, flexDirection: 'row', alignItems: 'center', gap: 11, paddingHorizontal: 10, paddingVertical: 9, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border },
  batchResearchRowSelected: { backgroundColor: '#FAF8FF' },
  selectionBox: { width: 22, height: 22, flexShrink: 0, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 6, backgroundColor: colors.surface },
  selectionBoxActive: { borderColor: '#7C3AED', backgroundColor: '#7C3AED' },
  batchActionBar: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    marginBottom: 10,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  batchActionCount: { flex: 1, color: colors.text, fontSize: 13, fontWeight: '800' },
  batchActionButton: { minHeight: 34, justifyContent: 'center', paddingHorizontal: 11, borderRadius: 8, backgroundColor: colors.surfaceSoft },
  batchActionText: { color: colors.text, fontSize: 12, fontWeight: '800' },
  batchDangerButton: { minHeight: 34, justifyContent: 'center', paddingHorizontal: 11, borderRadius: 8, backgroundColor: '#FDF0F0' },
  batchDangerText: { color: '#A33F3F', fontSize: 12, fontWeight: '800' },
  batchCloseButton: { width: 34, minHeight: 34, alignItems: 'center', justifyContent: 'center' },
  selectableRowActive: { borderColor: '#B8A6DD', backgroundColor: '#FAF8FF' },
  qaOrganizationStatus: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 8 },
  qaOrganizationPulse: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#7C3AED' },
  qaOrganizationEmpty: { minHeight: 56, flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 10 },
  qaOrganizationFailure: { flexDirection: 'column', alignItems: 'stretch', gap: 10 },
  qaPairCard: { gap: 7, paddingHorizontal: 8, paddingVertical: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border, borderRadius: 8 },
  qaPairCardActive: { backgroundColor: '#F7F4FD' },
  qaPairMetaRow: { minHeight: 28, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  qaPairIdentity: { minWidth: 0, flex: 1, flexDirection: 'row', alignItems: 'center', gap: 6 },
  qaPairIndex: { overflow: 'hidden', borderRadius: 5, paddingHorizontal: 6, paddingVertical: 3, color: '#6D55A3', backgroundColor: '#F1EDFA', fontSize: 10, fontWeight: '900', fontVariant: ['tabular-nums'] },
  qaPairSpeaker: { color: colors.textMuted, fontSize: 11, fontWeight: '800' },
  qaPairQuestion: { color: colors.text, fontSize: 15, lineHeight: 22, fontWeight: '800' },
  qaPairAnswer: { color: colors.text, fontSize: 14, lineHeight: 23 },
  qaExpandAction: { minHeight: 28, justifyContent: 'center' },
  qaLowConfidence: { overflow: 'hidden', color: '#946D35', fontSize: 10, backgroundColor: '#FFF7E8', paddingHorizontal: 6, paddingVertical: 3, borderRadius: 5 },
  transcriptWaveButton: { flexShrink: 0, minWidth: 78, minHeight: 28, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, borderRadius: 7, paddingHorizontal: 7, backgroundColor: '#F3F4F6' },
  transcriptWaveButtonActive: { backgroundColor: '#EEE8FA' },
  transcriptWaveButtonDisabled: { opacity: 0.42 },
  transcriptWaveTime: { flexShrink: 0, minWidth: 32, color: colors.textMuted, fontSize: 10, fontWeight: '700', fontVariant: ['tabular-nums'] },
  transcriptWaveTimeActive: { color: '#5E4A8A' },
  transcriptMiniWaveBarActive: { backgroundColor: '#6D55A3' },
  groupTopicTurns: { paddingTop: 2 },
  groupTopicTurn: { gap: 7, paddingVertical: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border },
  groupTopicTurnHeader: { minHeight: 28, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  groupTopicSpeakerRow: { minWidth: 0, flex: 1, flexDirection: 'row', alignItems: 'center', gap: 6 },
  groupTopicTurnIndex: { width: 24, height: 24, overflow: 'hidden', borderRadius: 12, color: '#FFFFFF', backgroundColor: '#A7B6C8', fontSize: 11, lineHeight: 24, fontWeight: '900', textAlign: 'center', fontVariant: ['tabular-nums'] },
  groupTopicTurnIndexSelf: { backgroundColor: '#8B72D8' },
  groupTopicTurnIndexFacilitator: { backgroundColor: '#70A8C8' },
  groupTopicSpeaker: { flexShrink: 1, color: colors.textMuted, fontSize: 12, fontWeight: '800' },
  groupTopicSpeakerSelf: { color: '#5E4A8A' },
  groupTopicRole: { flexShrink: 0, color: colors.textMuted, fontSize: 10, fontWeight: '700' },
  groupTopicTurnText: { color: colors.text, fontSize: 14, lineHeight: 23 },
  groupTopicCopyAction: { flexShrink: 0, width: 28, minHeight: 28, alignItems: 'center', justifyContent: 'center' },
  exportChoiceRow: { flexDirection: 'row', gap: 8 },
  exportChoice: { flex: 1, minHeight: 46, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: 9, backgroundColor: colors.surface },
  exportChoiceActive: { borderColor: '#9B87C9', backgroundColor: '#F5F3FF' },
  exportChoiceText: { color: colors.textMuted, fontSize: 13, fontWeight: '800' },
  exportChoiceTextActive: { color: '#5E4A8A' },
  exportToggleRow: { minHeight: 62, flexDirection: 'row', alignItems: 'center', gap: 11, paddingHorizontal: 12, paddingVertical: 10, borderRadius: 9, backgroundColor: colors.surfaceSoft },
  offerCompareToolbar: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 10, paddingHorizontal: 2 },
  offerCompareRow: { minHeight: 68, flexDirection: 'row', alignItems: 'center', gap: 11, paddingVertical: 12, paddingHorizontal: 10, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border, borderRadius: 8 },
  offerComparisonPanel: { gap: 10, marginBottom: 16, padding: 14, borderWidth: StyleSheet.hairlineWidth, borderColor: '#DED5F2', borderRadius: 12, backgroundColor: '#FAF8FF' },
  offerComparisonCard: { gap: 6, paddingVertical: 11, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#E8E1F2' },
  offerComparisonValue: { color: colors.text, fontSize: 17, fontWeight: '900' },
  offerBestTag: { overflow: 'hidden', color: '#047857', fontSize: 11, fontWeight: '800', backgroundColor: '#ECFDF5', paddingHorizontal: 7, paddingVertical: 3, borderRadius: 6 },
  offerCostText: { color: '#9A5B44', fontSize: 12, lineHeight: 18 },
  nextRoundAction: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 10, paddingHorizontal: 12, paddingVertical: 10, borderRadius: 10, backgroundColor: '#EFF6FF' },
  researchCurrentLabel: { overflow: 'hidden', borderRadius: 6, paddingHorizontal: 7, paddingVertical: 4, color: '#5B3B91', backgroundColor: '#EEE8FF', fontSize: 11, fontWeight: '800' },
  linkedJobBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    minHeight: 48,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
  },
  linkedJobTitle: { color: colors.text, fontSize: 13, fontWeight: '800', lineHeight: 18 },
  linkedJobMeta: { color: colors.textMuted, fontSize: 11, lineHeight: 16 },
  jobDetailPanel: {
    gap: 12,
    padding: 16,
    backgroundColor: colors.surface,
  },
  backButton: {
    alignSelf: 'flex-start',
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    justifyContent: 'center',
    borderRadius: 12,
    paddingHorizontal: 12,
    backgroundColor: colors.surface,
  },
  backButtonText: { color: colors.primaryDeep, fontSize: 15, fontWeight: '800' },
  dataPanel: {
    gap: 8,
    padding: 16,
    backgroundColor: colors.surface,
  },
  profileSummaryCard: {
    minHeight: 104,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    padding: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: colors.surface,
  },
  profileAvatar: {
    width: 56,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 28,
    backgroundColor: colors.primaryLight,
  },
  profileAvatarText: { color: colors.primaryDeep, fontSize: 20, fontWeight: '800' },
  profileSummaryCopy: { flex: 1, gap: 4 },
  profileSummaryTitle: { color: colors.text, fontSize: 18, fontWeight: '800', lineHeight: 24 },
  profileSummaryMeta: { color: colors.textMuted, fontSize: 13, lineHeight: 18 },
  localStatusRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 2 },
  localStatusDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.success },
  localStatusText: { color: colors.textMuted, fontSize: 12, fontWeight: '600' },
  profileStatGrid: { flexDirection: 'row', gap: 8 },
  analysisColumns: { flexDirection: 'row', gap: 1, backgroundColor: colors.border },
  analysisColumn: { flex: 1, gap: 12, padding: 14, backgroundColor: colors.surface },
  analysisColumnTitle: { color: colors.text, fontSize: 14, fontWeight: '800' },
  analysisDataRow: { gap: 5 },
  analysisDataHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 6 },
  analysisDataLabel: { flex: 1, color: colors.textMuted, fontSize: 12 },
  analysisDataValue: { color: colors.text, fontSize: 12, fontWeight: '800' },
  analysisPercent: { minWidth: 36, overflow: 'hidden', borderRadius: 5, paddingHorizontal: 5, paddingVertical: 2, color: colors.primaryDeep, backgroundColor: colors.primaryLight, fontSize: 10, fontWeight: '800', textAlign: 'center' },
  analysisBar: { height: 8, overflow: 'hidden', borderRadius: 4, backgroundColor: colors.surfaceSoft },
  analysisBarFill: { height: 8, borderRadius: 4, backgroundColor: colors.primary },
  sheetDismissButton: { alignSelf: 'flex-end', minHeight: 40, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18, paddingVertical: 8, borderWidth: StyleSheet.hairlineWidth, borderColor: colors.border, borderRadius: 8, backgroundColor: colors.surfaceSoft },
  sheetDismissButtonText: { color: colors.primaryDeep, fontSize: 14, fontWeight: '800' },
  inlineInfoGrid: { flexDirection: 'row', gap: 10 },
  profileStatItem: {
    flex: 1,
    minHeight: 72,
    justifyContent: 'space-between',
    padding: 10,
    borderRadius: 14,
    backgroundColor: colors.surfaceSoft,
  },
  infoBox: {
    gap: 4,
    flex: 1,
    paddingVertical: 8,
  },
  infoValueUnset: { color: colors.textMuted, fontWeight: '600' },
  readingCard: {
    gap: 8,
    paddingVertical: 4,
  },
  readingTitle: { color: colors.primaryDeep, fontSize: 13, fontWeight: '800' },
  readingText: { color: colors.text, fontSize: 15, lineHeight: 23 },
  noticeBox: { minHeight: 68, flexDirection: 'row', alignItems: 'center', gap: 10, padding: 14, borderWidth: StyleSheet.hairlineWidth, borderColor: '#E8DCCB', borderRadius: 8, backgroundColor: '#FFFBF5' },
  noticeTitle: { color: '#84662F', fontSize: 12, fontWeight: '800' },
  noticeText: { marginTop: 3, color: colors.text, fontSize: 14, lineHeight: 20, fontWeight: '700' },
  intentPanel: { gap: 9, paddingTop: 4 },
  intentOptions: { flexDirection: 'row', gap: 8 },
  intentOption: { flex: 1, minHeight: 38, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: 8, backgroundColor: colors.surface },
  intentOptionActive: { borderColor: colors.primaryDeep, backgroundColor: colors.primaryDeep },
  intentOptionText: { color: colors.textMuted, fontSize: 13, fontWeight: '800' },
  intentOptionTextActive: { color: colors.surface },
  draftList: { maxHeight: 360 },
  ocrProgressPanel: { gap: 12, paddingVertical: 26 },
  draftSelectionToolbar: { flexDirection: 'row', justifyContent: 'flex-end', gap: 20, paddingVertical: 4 },
  discardTextAction: { color: '#9F4E45', fontSize: 13, fontWeight: '800' },
  draftKind: { marginBottom: 3, color: colors.primary, fontSize: 11, fontWeight: '900' },
  draftCard: {
    gap: 8,
    padding: 14,
    borderRadius: 8,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  draftCardActive: {
    borderColor: colors.primary,
    backgroundColor: colors.surfaceSoft,
  },
  draftJdPreview: { color: colors.text, fontSize: 13, lineHeight: 19 },
  interviewLinkNotice: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 9, paddingVertical: 7, borderRadius: 7, backgroundColor: '#ECFDF5' },
  interviewLinkNoticeText: { flex: 1, color: '#047857', fontSize: 11, lineHeight: 16, fontWeight: '800' },
  interviewLinkNoticeTextNew: { color: '#6D28D9' },
  inputCounter: { alignSelf: 'flex-end', color: colors.textMuted, fontSize: 11 },
  resumeContentArea: { minHeight: 220, padding: 14, borderWidth: 1, borderColor: colors.border, borderRadius: 8, color: colors.text, backgroundColor: colors.surface, fontSize: 14, lineHeight: 21 },
  hrAssistantBody: { gap: 14, padding: 16 },
  hrContextRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  hrContextIcon: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center', borderRadius: 8, backgroundColor: '#F5F3FF' },
  hrMissingContext: { flexDirection: 'row', alignItems: 'center', gap: 10, padding: 12, borderWidth: 1, borderColor: '#E8DCCB', borderRadius: 8, backgroundColor: '#FFFBF5' },
  hrMissingContextCopy: { flex: 1, minWidth: 0, gap: 4 },
  hrMissingContextAction: { minHeight: 34, flexShrink: 0, flexDirection: 'row', alignItems: 'center', gap: 2, paddingHorizontal: 8, borderRadius: 7, backgroundColor: '#F5F3FF' },
  hrMissingContextActionText: { color: '#6D28D9', fontSize: 12, lineHeight: 18, fontWeight: '800' },
  hrQuestionInput: { minHeight: 112, padding: 14, borderWidth: 1, borderColor: colors.border, borderRadius: 8, color: colors.text, backgroundColor: colors.surface, fontSize: 15, lineHeight: 22 },
  hrGenerateButton: { minHeight: 46, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, paddingHorizontal: 16, borderWidth: 1, borderColor: '#DDD6FE', borderRadius: 8, backgroundColor: '#F5F3FF' },
  hrGenerateButtonText: { color: '#6D28D9', fontSize: 15, fontWeight: '800' },
  hrRecordList: { gap: 12, padding: 12 },
  hrAnswerCard: { gap: 8, padding: 16, borderWidth: StyleSheet.hairlineWidth, borderColor: '#E5E7EB', borderRadius: 8, backgroundColor: colors.surface },
  hrQuestionLabel: { color: colors.textMuted, fontSize: 11, fontWeight: '800' },
  hrQuestionText: { color: colors.text, fontSize: 14, lineHeight: 21, fontWeight: '700' },
  hrAnswerDivider: { height: StyleSheet.hairlineWidth, marginVertical: 2, backgroundColor: colors.border },
  hrAnswerLabel: { color: '#6D28D9', fontSize: 11, fontWeight: '900' },
  hrAnswerText: { color: colors.text, fontSize: 15, lineHeight: 23 },
  hrEvidenceWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  hrEvidenceTag: { overflow: 'hidden', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, color: '#4B5563', backgroundColor: '#F3F4F6', fontSize: 11, fontWeight: '700' },
  hrCaution: { padding: 10, borderRadius: 6, color: '#9A3412', backgroundColor: '#FFF7ED', fontSize: 12, lineHeight: 18 },
  hrAnswerActions: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  hrAnswerActionButtons: { flexDirection: 'row', gap: 8 },
  ocrConfidenceRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 5, marginTop: 7 },
  ocrConfidenceTag: { overflow: 'hidden', borderRadius: 5, paddingHorizontal: 6, paddingVertical: 3, color: '#4B5563', backgroundColor: '#F3F4F6', fontSize: 10, fontWeight: '700' },
  ocrConfidenceTagLow: { color: '#9A3412', backgroundColor: '#FFF7ED' },
  duplicateActionButton: { minHeight: 34, alignItems: 'center', justifyContent: 'center', marginTop: 9, borderRadius: 8, backgroundColor: '#EFF6FF' },
  duplicateActionText: { color: '#1D4ED8', fontSize: 12, fontWeight: '800' },
  selectionMark: {
    width: 28,
    height: 28,
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  selectionMarkActive: { borderColor: colors.primaryDeep, color: colors.surface, backgroundColor: colors.primaryDeep },
  timelineRow: {
    gap: 4,
    padding: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
  },
  timelineItem: { minHeight: 76, flexDirection: 'row', paddingHorizontal: 16, backgroundColor: colors.surface },
  timelineRail: { width: 24, alignItems: 'center' },
  timelineDotShell: { width: 18, height: 18, alignItems: 'center', justifyContent: 'center', marginTop: 15, borderRadius: 9 },
  timelineDotShellCurrent: { backgroundColor: colors.primaryLight },
  timelineDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.primaryDeep },
  timelineDotEnded: { backgroundColor: colors.textMuted },
  timelineLine: { flex: 1, width: 1, backgroundColor: colors.border },
  timelineContent: { flex: 1, gap: 3, paddingVertical: 14, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border },
  exportText: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 21,
  },
  exportArea: {
    minHeight: 240,
    padding: 16,
    color: colors.text,
    backgroundColor: colors.surface,
    fontSize: 12,
    lineHeight: 18,
  },
  compactFilterBlock: { gap: 8, paddingHorizontal: 4, paddingVertical: 8 },
  activeFilterText: { alignSelf: 'flex-start', marginTop: 2, color: colors.textMuted, fontSize: 12, lineHeight: 18 },
  filterGroup: { gap: 8 },
  dateRangeBlock: { gap: 10 },
  dateRangeDropdown: { flexShrink: 0, alignItems: 'flex-end' },
  dateRangeDropdownButton: { minWidth: 40, minHeight: 40, maxWidth: 112, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingHorizontal: 10, paddingVertical: 7, borderWidth: 1, borderColor: colors.border, borderRadius: 8, backgroundColor: colors.surface },
  dateRangeDropdownButtonActive: { borderColor: '#BFDBFE', backgroundColor: '#EFF6FF' },
  dateRangeDropdownText: { flexShrink: 1, color: colors.textMuted, fontSize: 12, lineHeight: 18, fontWeight: '700' },
  dateRangeDropdownTextActive: { color: '#1D4ED8' },
  dateRangeFields: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  dateRangeField: { flex: 1, minHeight: 54, justifyContent: 'center', gap: 2, paddingHorizontal: 12, paddingVertical: 8, borderWidth: 1, borderColor: colors.border, borderRadius: 8, backgroundColor: colors.surface },
  archiveRow: { minHeight: 70, flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border, backgroundColor: colors.surface },
  smallSecondaryButton: { minHeight: 36, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 12, paddingVertical: 8, borderWidth: 1, borderColor: colors.border, borderRadius: 8, backgroundColor: colors.surfaceSoft },
  smallSecondaryButtonText: { color: colors.primaryDeep, fontSize: 12, fontWeight: '800' },
  emptyState: {
    minHeight: 76,
    justifyContent: 'center',
    padding: 16,
    backgroundColor: colors.surface,
  },
  emptyStateText: { color: colors.textMuted, fontSize: 14, lineHeight: 20 },
});
